Properly start abstractions also at function exit locations
Currently we only started the abstraction from the function entry
locations. This produced wrong proofs, since an important case was
missing, namely when we returned from the function with an arbitrary
return value. This could be seen for the simple program:

```c
int id(int x) {
  if (x==0) return 0;
  return id(x-1) + 1;
}

int main(void) {
  int result = id(5);
  if (result == 5) {
    ERROR: {reach_error();abort();}
  }
}
```

where when we do not return an arbitrary value at some point from id,
then always 0 is returned which would complete a 1-inductive proof
always, since the only possible value is 1.