Catch NoClassDefFoundError to prevent CPAChecker from crashing on GAE.
Google App Engine does not allow to use classes from the package
java.lang.management. Therefore it throws a NoClassDefFoundError if this is
attempted regardless. To prevent CPAChecker from crashing in this case the error
is caught and the event is logged.


git-svn-id: https://svn.sosy-lab.org/software/cpachecker/branches/gae-port@10012 4712c6d2-40bb-43ae-aa4b-fec3f1bdfe4c