Benchmark-Webclient: catch AttributeError.
Killing a running benchmark can cause the SSE-connection to terminate and throw an exception like
"SSE connection terminated: 'NoneType' object has no attribute 'readinto'".
We want to terminate our script normally afterwards.

(Most of this commit is just whitespace-change.)

git-svn-id: https://svn.sosy-lab.org/software/cpachecker/trunk@30290 4712c6d2-40bb-43ae-aa4b-fec3f1bdfe4c